config/routes.rb
Rails.application.routes.draw do
  get 'travelagent/index'

  resources :payments
  resources :reservations
  resources :cruises
  resources :cabins
  resources :ships
  resources :credit_cards
  resources :addresses
  resources :customers

  root 'travelagent#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cabin.rb
class Cabin < ApplicationRecord
  belongs_to :ship
  has_and_belongs_to_many :reservations
end

app/controllers/cabins_controller.rb
class CabinsController < ApplicationController
  before_action :set_cabin, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  # GET /cabins
  # GET /cabins.json
  def index
    @cabins = Cabin.all
  end

  # GET /cabins/1
  # GET /cabins/1.json
  def show
  end

  # GET /cabins/new
  def new
    @cabin = Cabin.new
    @ships = Ship.all
  end

  # GET /cabins/1/edit
  def edit
    @ships = Ship.all
  end

  # POST /cabins
  # POST /cabins.json
  def create
    @cabin = Cabin.new(cabin_params)

    respond_to do |format|
      if @cabin.save
        format.html { redirect_to @cabin, notice: 'Cabin was successfully created.' }
        format.json { render :show, status: :created, location: @cabin }
      else
        format.html { render :new }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cabins/1
  # PATCH/PUT /cabins/1.json
  def update
    respond_to do |format|
      if @cabin.update(cabin_params)
        format.html { redirect_to @cabin, notice: 'Cabin was successfully updated.' }
        format.json { render :show, status: :ok, location: @cabin }
      else
        format.html { render :edit }
        format.json { render json: @cabin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cabins/1
  # DELETE /cabins/1.json
  def destroy
    @cabin.destroy
    respond_to do |format|
      format.html { redirect_to cabins_url, notice: 'Cabin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cabin
      @cabin = Cabin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cabin_params
      params.require(:cabin).permit(:name, :beds, :deck, :ship_id)
    end
end

app/helpers/cabins_helper.rb
module CabinsHelper
end

app/views/cabins/_form.html.erb
<%= form_with(model: cabin, local: true) do |form| %>
  <% if cabin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cabin.errors.count, "error") %> prohibited this cabin from being saved:</h2>

      <ul>
      <% cabin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cabin_name %>
  </div>

  <div class="field">
    <%= form.label :beds %>
    <%= form.number_field :beds, id: :cabin_beds %>
  </div>

  <div class="field">
    <%= form.label :deck %>
    <%= form.number_field :deck, id: :cabin_deck %>
  </div>

  <div class="field">
    <em><%= form.label :ship_id %></em>
    <%= form.collection_select(:ship_id, @ships, :id, :name ) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cabins/edit.html.erb
<h1>Editing Cabin</h1>

<%= render 'form', cabin: @cabin %>

<%= link_to 'Show', @cabin %> |
<%= link_to 'Back', cabins_path %>

app/views/cabins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cabins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Beds</th>
      <th>Deck</th>
      <th>Ship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cabins.each do |cabin| %>
      <tr>
        <td><%= cabin.name %></td>
        <td><%= cabin.beds %></td>
        <td><%= cabin.deck %></td>
        <td><%= cabin.ship.name %></td>
        <td><%= link_to 'Show', cabin %></td>
        <td><%= link_to 'Edit', edit_cabin_path(cabin) %></td>
        <td><%= link_to 'Destroy', cabin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cabin', new_cabin_path %>

app/views/cabins/new.html.erb
<h1>New Cabin</h1>

<%= render 'form', cabin: @cabin %>

<%= link_to 'Back', cabins_path %>

app/views/cabins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cabin.name %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @cabin.beds %>
</p>

<p>
  <strong>Deck:</strong>
  <%= @cabin.deck %>
</p>

<p>
  <strong>Ship:</strong>
  <%= @cabin.ship.name %>
</p>

<%= link_to 'Edit', edit_cabin_path(@cabin) %> |
<%= link_to 'Back', cabins_path %>