config/routes.rb
Rails.application.routes.draw do
  get 'travelagent/index'

  resources :payments
  resources :reservations
  resources :cruises
  resources :cabins
  resources :ships
  resources :credit_cards
  resources :addresses
  resources :customers

  root 'travelagent#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :address, :dependent => :destroy
  has_many :credit_cards
  has_many :reservations
  validates :last_name, :first_name, :has_good_credit, :paid, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_if_not_found
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save

        @customer.create_address
        
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :has_good_credit, :paid)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :customer_last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :customer_first_name %>
  </div>

  <div class="field">
    <%= form.label :has_good_credit %>
    <%= form.number_field :has_good_credit, id: :customer_has_good_credit %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid, id: :customer_paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Has good credit</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.last_name %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.has_good_credit %></td>
        <td><%= customer.paid %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Has good credit:</strong>
  <%= @customer.has_good_credit %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @customer.paid %>
</p>

<p> <b>Address:</b> 
  <%= "#{@customer.address.street}" %>,
  <%= "#{@customer.address.city}" %>
  <%= "#{@customer.address.postcode}" %>
</p>

<%= link_to 'Edit', edit_address_path( @customer.address.id ) %><br>

<p>
  <b>Credit Cards:</b> </p>
  <% @customer.credit_cards.each do |cc| %>
<p>
  <%= cc.number %>
  <%= cc.name_on_card %>
  <%= cc.organisation %>
  <%= cc.exp_date %>
</p>
<% end %>

<p><%= link_to 'Add a Credit Card', controller: "credit_cards", action: "new", customer_id: @customer.id %></p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>